spring.application.name=fitflow-service
spring.datasource.url=jdbc:postgresql://localhost:5432/fitflow_db
spring.datasource.username=fitflow
spring.datasource.password=fitflow
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
# Enable logging of SQL parameters
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

security.jwt.expiration-time=86400000
# 24 horas em milissegundos

